defaults:
  - _self_
  - problem: tsp_gls
  - override hydra/output: local

hydra:
  job:
    chdir: True
# The chosen algorithm
algorithm: eoh

# LLM parameters
model: mistral/codestral-latest # LLM model
temperature: 1  # temperature for chat completion

# Main GA loop parameters
max_fe: 500 # maximum number of function evaluations
pop_size: 10 # population size for GA
init_pop_size: 30 # initial population size for GA/each island
mutation_rate: 0.5 # mutation rate for GA
timeout: 30 # timeout for evaluation of a single heuristic

# Harmony search
hm_size: 5
hmcr: 0.7
par: 0.5
bandwidth: 0.2
max_iter: 5

# Island parameter
n_island: 2
migration_interval: 3
migration_size: 3
